// GENERATED by scripts/publish-portraits.mjs — do not hand-edit.
// YouTube video ids with a guest portrait at public/images/guests/<id>.jpg, cropped from
// that episode's thumbnail by scripts/crop-portraits.ps1.
//
// Two filters stand between a thumbnail and this list. Every crop was classified by
// layout in scripts/portrait-templates.csv, because the show has used eight thumbnail
// layouts and the host is not always on the same side. Then every crop was reviewed by eye
// and the weak ones listed in scripts/portrait-rejects.txt — the source is video-call
// stills, so roughly half do not survive as headshots.
export const GUEST_PORTRAITS = new Set<string>([
  "09RlEVnHfSM",
  "0f3_et0tJhI",
  "1BrwUVr532A",
  "354jVImN6AU",
  "5GhsgOU5kdI",
  "77KwnIXkjlM",
  "7dQknaDHrg8",
  "ASAKXCrhQyo",
  "CUbP12ucC5A",
  "ChhVEmQMg18",
  "K6yOa3v1u0Y",
  "LslRksGWsfw",
  "MSO4l5y8d34",
  "MpKNRw8NTkI",
  "OWCzHN41pYw",
  "OkIxqUQX7ac",
  "P8DKKlbXyag",
  "PgnuDkg3IQI",
  "QYWgA71hbOQ",
  "SRlpOgVl_-c",
  "U65aKoyiX08",
  "X2awBuxrkf8",
  "XrolwTdPLcU",
  "azaH2Jc3giE",
  "cY21_0cufeM",
  "cfjbMBtV964",
  "fEU7cM6PRr4",
  "iDO8lv9Xz8o",
  "iZ-RkOJK5uo",
  "jIPVjkPVFtk",
  "jz3nV73J6jc",
  "kmxueK7i4x4",
  "mGeKes9UDV4",
  "oOA9CTlrMBc",
  "ovc6gH0iLW8",
  "tn_KPfopNxM",
  "zbAgzN2WjME",
  "zu1PsliXwmw",
]);
