// GENERATED by scripts/build-guest-portraits.mjs — do not hand-edit.
// YouTube video ids with a verified guest portrait at public/images/guests/<id>.jpg,
// cropped from that episode's thumbnail.
//
// The show has used several thumbnail templates and the host is not always on the same
// side, so every crop was checked by eye against a contact sheet before shipping.
// Episodes whose thumbnail is a raw video-call grid are excluded — their layout varies,
// and a bad guess would put the host's face under a guest's name.
export const GUEST_PORTRAITS = new Set<string>([
  "09RlEVnHfSM",
  "1BrwUVr532A",
  "354jVImN6AU",
  "514Ao55HLko",
  "6OQ2fWBvZmw",
  "77KwnIXkjlM",
  "ASAKXCrhQyo",
  "CUbP12ucC5A",
  "ChhVEmQMg18",
  "K6yOa3v1u0Y",
  "LZQCVGajdac",
  "LslRksGWsfw",
  "MSO4l5y8d34",
  "MpKNRw8NTkI",
  "OWCzHN41pYw",
  "P8DKKlbXyag",
  "QYWgA71hbOQ",
  "SRlpOgVl_-c",
  "TPNEt1Y1klA",
  "U65aKoyiX08",
  "X2awBuxrkf8",
  "XrolwTdPLcU",
  "fEU7cM6PRr4",
  "iDO8lv9Xz8o",
  "iZ-RkOJK5uo",
  "jIPVjkPVFtk",
  "kmxueK7i4x4",
  "oOA9CTlrMBc",
  "ovc6gH0iLW8",
  "pgetmiZqsZw",
  "tn_KPfopNxM",
  "zbAgzN2WjME",
]);
