// GENERATED — YouTube videos for the @GoodGarbage channel, merged from the Apify scrape
// and the two upload spreadsheets in Appspodcast. Supplies per-episode thumbnails,
// which the RSS feed does not carry (its itunes:image is show art).
export interface YoutubeVideo {
  videoId: string;
  titles: string[];
  thumbnail: string;
  date: string;
  apple: string | null;
}

export const YOUTUBE_VIDEOS: YoutubeVideo[] = [
  {"videoId":"6OQ2fWBvZmw","titles":["Meta Materials & Bioplastics in Packaging | Vaibhav Anand on Scaling Sustainability"],"thumbnail":"https://i.ytimg.com/vi/6OQ2fWBvZmw/maxresdefault.jpg","date":"2026-04-30","apple":"https://podcasts.apple.com/us/podcast/meta-materials-bioplastics-in-packaging-vaibhav-anand/id1613337676?i=1000764634882"},
  {"videoId":"LZQCVGajdac","titles":["The Truth About Sustainable Packaging with Sandeep Kulkarni"],"thumbnail":"https://i.ytimg.com/vi/LZQCVGajdac/maxresdefault.jpg","date":"2026-04-16","apple":"https://podcasts.apple.com/us/podcast/the-truth-about-sustainable-packaging-with/id1613337676?i=1000761875157"},
  {"videoId":"1BrwUVr532A","titles":["Designing Packaging That Disappears: The NakedPak Approach with Naama Nicotra"],"thumbnail":"https://i.ytimg.com/vi/1BrwUVr532A/maxresdefault.jpg","date":"2026-02-26","apple":"https://podcasts.apple.com/us/podcast/designing-packaging-that-disappears-the-nakedpak/id1613337676?i=1000751774071"},
  {"videoId":"QYWgA71hbOQ","titles":["From Pulp to Performance: The Science of Paper with Dr. Alexey Vishtal"],"thumbnail":"https://i.ytimg.com/vi/QYWgA71hbOQ/maxresdefault.jpg","date":"2026-02-14","apple":"https://podcasts.apple.com/us/podcast/from-pulp-to-performance-the-science-of-paper-with/id1613337676?i=1000749699719"},
  {"videoId":"CUbP12ucC5A","titles":["Can Seaweed Replace Plastic? With Neha Jain"],"thumbnail":"https://i.ytimg.com/vi/CUbP12ucC5A/maxresdefault.jpg","date":"2026-02-03","apple":"https://podcasts.apple.com/us/podcast/can-seaweed-replace-plastic-with-neha-jain/id1613337676?i=1000747895994"},
  {"videoId":"ASAKXCrhQyo","titles":["Soil, Soul and Systems Change: A Conversation with Sammy Davies"],"thumbnail":"https://i.ytimg.com/vi/ASAKXCrhQyo/maxresdefault.jpg","date":"2025-12-27","apple":"https://podcasts.apple.com/us/podcast/soil-soul-and-systems-change-a-conversation/id1613337676?i=1000742873506"},
  {"videoId":"PgnuDkg3IQI","titles":["Why the Future of Sustainability is in India with Avantika Saraogi"],"thumbnail":"https://i.ytimg.com/vi/PgnuDkg3IQI/maxresdefault.jpg","date":"2025-12-04","apple":"https://podcasts.apple.com/us/podcast/why-the-future-of-sustainability-is-in-india/id1613337676?i=1000739743296"},
  {"videoId":"pgetmiZqsZw","titles":["Creating Environmental Art with Benjamin Von Wong"],"thumbnail":"https://i.ytimg.com/vi/pgetmiZqsZw/maxresdefault.jpg","date":"2025-11-20","apple":null},
  {"videoId":"TPNEt1Y1klA","titles":["This Artist is Cleaning the Planet with Benjamin Von Wong"],"thumbnail":"https://i.ytimg.com/vi/TPNEt1Y1klA/maxresdefault.jpg","date":"2025-11-20","apple":null},
  {"videoId":"0DXpeSkJAfA","titles":["Around The World of Packaging with Alex Moore"],"thumbnail":"https://i.ytimg.com/vi/0DXpeSkJAfA/maxresdefault.jpg","date":"2025-10-30","apple":null},
  {"videoId":"iDO8lv9Xz8o","titles":["Why Composting is having a REVOLUTION with the Italian Stallion, Frank Franciosi | Good Garbage"],"thumbnail":"https://i.ytimg.com/vi/iDO8lv9Xz8o/maxresdefault.jpg","date":"2025-10-24","apple":null},
  {"videoId":"kmxueK7i4x4","titles":["How PROTESTING led to a CLEANER PLANET with Caroline DeLoach | Good Garbage Podcast"],"thumbnail":"https://i.ytimg.com/vi/kmxueK7i4x4/maxresdefault.jpg","date":"2025-10-09","apple":null},
  {"videoId":"LslRksGWsfw","titles":["From Forests to Finance with David Walker | Good Garbage Podcast"],"thumbnail":"https://i.ytimg.com/vi/LslRksGWsfw/maxresdefault.jpg","date":"2025-10-03","apple":null},
  {"videoId":"U65aKoyiX08","titles":["Chocolate's SWEET Path to SUSTAINABILITY with Keith Bearden | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/U65aKoyiX08/maxresdefault.jpg","date":"2025-09-12","apple":null},
  {"videoId":"zbAgzN2WjME","titles":["Tackling Plastic Pollution with ART & ACTIVISM with Dianna Cohen | Good Garbage Podcast"],"thumbnail":"https://i.ytimg.com/vi/zbAgzN2WjME/maxresdefault.jpg","date":"2025-08-28","apple":null},
  {"videoId":"354jVImN6AU","titles":["Biodynamic Roots to Eco-Friendly Solutions with Sigrid Svedberg | Good Garbage Podcast | Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/354jVImN6AU/maxresdefault.jpg","date":"2025-08-14","apple":null},
  {"videoId":"09RlEVnHfSM","titles":["Organically Understanding Value with Sunder Balakrishnan | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/09RlEVnHfSM/maxresdefault.jpg","date":"2025-07-31","apple":null},
  {"videoId":"ovc6gH0iLW8","titles":["The Impatient Entrepreneur: Lessons from Alvin Lim | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/ovc6gH0iLW8/maxresdefault.jpg","date":"2025-07-17","apple":null},
  {"videoId":"OWCzHN41pYw","titles":["USDA and the World of Biopolymers with William Orts | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/OWCzHN41pYw/maxresdefault.jpg","date":"2025-07-04","apple":null},
  {"videoId":"SRlpOgVl_-c","titles":["Packaging YOU can EAT with Marie Eric | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/SRlpOgVl_-c/maxresdefault.jpg","date":"2025-06-23","apple":null},
  {"videoId":"jIPVjkPVFtk","titles":["The Intersection of Curiosity and Sustainability with Kelly Williams | Good Garbage Podcast"],"thumbnail":"https://i.ytimg.com/vi/jIPVjkPVFtk/maxresdefault.jpg","date":"2025-06-06","apple":null},
  {"videoId":"oOA9CTlrMBc","titles":["Rethinking Materials with TerraSafe's Scott Bolin | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/oOA9CTlrMBc/maxresdefault.jpg","date":"2025-05-31","apple":null},
  {"videoId":"ChhVEmQMg18","titles":["Building a Brand with a Purpose with Pacha's Maddie Hamann | Good Garbage Podcast with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/ChhVEmQMg18/maxresdefault.jpg","date":"2025-05-05","apple":null},
  {"videoId":"fEU7cM6PRr4","titles":["How to PITCH Greentech, a masterclass | Simone Schuppan | Good Garbage with Ved Krishna"],"thumbnail":"https://i.ytimg.com/vi/fEU7cM6PRr4/maxresdefault.jpg","date":"2025-04-10","apple":null},
  {"videoId":"iZ-RkOJK5uo","titles":["Good Garbage with Ved Krishna: Sustainable Packaging in Eastern Europe with Angela Ivanova"],"thumbnail":"https://i.ytimg.com/vi/iZ-RkOJK5uo/maxresdefault.jpg","date":"2025-03-15","apple":null},
  {"videoId":"77KwnIXkjlM","titles":["Good Garbage with Ved Krishna: Elevating Sustainable Packaging with Rich Cohen"],"thumbnail":"https://i.ytimg.com/vi/77KwnIXkjlM/maxresdefault.jpg","date":"2025-03-02","apple":null},
  {"videoId":"tn_KPfopNxM","titles":["Good Garbage with Ved Krishna: Deconstructing Biochemistry in Packaging with Evan White"],"thumbnail":"https://i.ytimg.com/vi/tn_KPfopNxM/maxresdefault.jpg","date":"2025-02-17","apple":null},
  {"videoId":"K6yOa3v1u0Y","titles":["Good Garbage with Ved Krishna: From Greenhouse Gas to Green Polymers with Molly Morse"],"thumbnail":"https://i.ytimg.com/vi/K6yOa3v1u0Y/maxresdefault.jpg","date":"2025-01-31","apple":null},
  {"videoId":"XrolwTdPLcU","titles":["Good Garbage with Ved Krishna: Certifiably Compostable with Susan Thoman"],"thumbnail":"https://i.ytimg.com/vi/XrolwTdPLcU/maxresdefault.jpg","date":"2025-01-27","apple":null},
  {"videoId":"P8DKKlbXyag","titles":["Good Garbage with Ved Krishna: Bitten by the Sustainability Bug with Mounir Izallalen"],"thumbnail":"https://i.ytimg.com/vi/P8DKKlbXyag/maxresdefault.jpg","date":"2025-01-26","apple":null},
  {"videoId":"514Ao55HLko","titles":["Good Garbage with Ved Krishna: Sweet and Sustainable with Jeanyves Verdu & Norman Rice"],"thumbnail":"https://i.ytimg.com/vi/514Ao55HLko/maxresdefault.jpg","date":"2025-01-25","apple":null},
  {"videoId":"X2awBuxrkf8","titles":["Good Garbage with Ved Krishna: Accelerating Towards a Sustainable Future with Sanjay Monie"],"thumbnail":"https://i.ytimg.com/vi/X2awBuxrkf8/maxresdefault.jpg","date":"2025-01-24","apple":null},
  {"videoId":"MSO4l5y8d34","titles":["Good Garbage with Ved Krishna: Closures for a Cleaner Planet with Lars Sandberg"],"thumbnail":"https://i.ytimg.com/vi/MSO4l5y8d34/maxresdefault.jpg","date":"2025-01-23","apple":null},
  {"videoId":"5GhsgOU5kdI","titles":["Good Garbage with Ved Krishna: Breaking Barriers of Sustainable Packaging with Scott Segal"],"thumbnail":"https://i.ytimg.com/vi/5GhsgOU5kdI/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGFIgZShQMA8=&rs=AOn4CLBn8pd9vFkWovmxktPTGlRNvE_GlQ","date":"2024-11-07","apple":null},
  {"videoId":"MpKNRw8NTkI","titles":["Good Garbage with Ved Krishna: The Journey of Funding a Good Mission with Jenny Garbis"],"thumbnail":"https://i.ytimg.com/vi/MpKNRw8NTkI/maxresdefault.jpg","date":"2024-10-24","apple":null},
  {"videoId":"nW6CP6hVJ-4","titles":["Good Garbage with Ved Krishna: Disrupting the Food Packaging Industry with Ralph Bianculli"],"thumbnail":"https://i.ytimg.com/vi/nW6CP6hVJ-4/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGFsgZShMMA8=&rs=AOn4CLCmq8l4qmjEXbii13B1pfqwTc5ODQ","date":"2024-10-10","apple":null},
  {"videoId":"FPy3egZMk2M","titles":["Good Garbage with Ved Krishna: The Road Map to Compostables with Gary Smith & Richard Fine"],"thumbnail":"https://i.ytimg.com/vi/FPy3egZMk2M/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgTyhLMA8=&rs=AOn4CLA5-0oK2t32u1UoFKhlgFxr06-sbQ","date":"2024-09-26","apple":null},
  {"videoId":"uemlkozjhso","titles":["Good Garbage with Ved Krishna: More Than Resource Recovery with Elly Ventura & Erin Levine"],"thumbnail":"https://i.ytimg.com/vi/uemlkozjhso/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgZShlMA8=&rs=AOn4CLC-1Taq3hbe0sWvUSjOKTtG9ea8WQ","date":"2024-09-12","apple":null},
  {"videoId":"TA_daPDBcd0","titles":["Good Garbage with Ved Krishna: Systemic Sustainability Goals with Sander Defryut"],"thumbnail":"https://i.ytimg.com/vi/TA_daPDBcd0/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgTihDMA8=&rs=AOn4CLAsdEk5Ot7OMCIWMj8-hyrD_ee-5Q","date":"2024-08-30","apple":null},
  {"videoId":"mp-h_yvsG4Q","titles":["Good Garbage with Ved Krishna: Serving Packaging with Love with Ciara Lamia & Beau Whitney"],"thumbnail":"https://i.ytimg.com/vi/mp-h_yvsG4Q/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgYShWMA8=&rs=AOn4CLAHPNZgg9dYWRZR2rcOrbIdQ219Mg","date":"2024-08-28","apple":null},
  {"videoId":"fROmsJr8mMc","titles":["Good Garbage with Ved Krishna: Holistic Waste Diversion with Shaun Miller"],"thumbnail":"https://i.ytimg.com/vi/fROmsJr8mMc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgSShDMA8=&rs=AOn4CLDXHYsm_QA0ZdCpuLU-RW8SJ9vA5w","date":"2024-08-01","apple":null},
  {"videoId":"kn-EAXx_lIM","titles":["Good Garbage with Ved Krishna: Building the Right Barrier Chemistry with Romain Metivet"],"thumbnail":"https://i.ytimg.com/vi/kn-EAXx_lIM/hqdefault.jpg?sqp=-oaymwEmCOADEOgC8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgUChIMA8=&rs=AOn4CLDLJe9kPPlCr97FYk6C9lnJVLkFnw","date":"2024-07-18","apple":null},
  {"videoId":"QSY0cYhluEc","titles":["Good Garbage with Ved Krishna: The Plastic Crisis is a Gift with Sian Sutherland Part 2"],"thumbnail":"https://i.ytimg.com/vi/QSY0cYhluEc/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgTChAMA8=&rs=AOn4CLDWg9ETU2UH5db8m8hSA7feHlr-6Q","date":"2024-07-10","apple":null},
  {"videoId":"V0wAkKKbtyw","titles":["Good Garbage with Ved Krishna: The Myth of Recycling with Sian Sutherland Part 1"],"thumbnail":"https://i.ytimg.com/vi/V0wAkKKbtyw/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgTihBMA8=&rs=AOn4CLAf5foaN5rT5VBf-a-E5obqmqA11A","date":"2024-06-21","apple":null},
  {"videoId":"1tvSXMkW0JI","titles":["Good Garbage with Ved Krishna: An Innovative Future is Not Plastic with Pierre Paslier"],"thumbnail":"https://i.ytimg.com/vi/1tvSXMkW0JI/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGGUgUyhJMA8=&rs=AOn4CLB69NEZ0wHot_8AlT-GctNzQ9q47g","date":"2024-06-08","apple":null},
  {"videoId":"ilIkmhhwFpY","titles":["Good Garbage with Ved Krishna: Compost Communication with Jennifer Trent & Linda Waldt"],"thumbnail":"https://i.ytimg.com/vi/ilIkmhhwFpY/maxresdefault.jpg","date":"2024-05-28","apple":null},
  {"videoId":"b023zAzuxik","titles":["Good Garbage with Ved Krishna: The Solution for Pollution with Brad Laporte and Michael Winters"],"thumbnail":"https://i.ytimg.com/vi/b023zAzuxik/maxresdefault.jpg","date":"2024-05-10","apple":null},
];
